local import_utils = require('user.importutils')
import_utils.require('lspconfig')
import_utils.require("user.lsp.lsp-installer")
import_utils.require("user.lsp.handlers").setup()
import_utils.require("user.lsp.null-ls")
import_utils.require("user.lsp.lspkind")
print("lsp initialization complete")
